name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Configure Vercel Project
        run: |
          mkdir -p .vercel
          cat << 'EOF' > .vercel/project.json
          {
            "projectId": "prj_182usg97CJm3IpvkcN8vcZthMQVm",
            "orgId": "team_aWKIz3qizxZbfe5jEk8fa9J2"
          }
          EOF

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
